enum IpcEvents {
  PLAY = 'PLAY',
  DRAW = 'DRAW',
  ETB = 'ETB',
  IMPORT = 'IMPORT',
  DELETE_DECK = 'DELETE_DECK',
  DECK_LOADED = 'DECK_LOADED',
  PLAY_TEST = 'PLAY_TEST',
  GET_DECKS = 'GET_DECKS',
  SEARCH_CARDS = 'SEARCH_CARDS',
  SEARCH_RESULTS = 'SEARCH_RESULTS',
  GET_SETS = 'GET_SETS',
}

export default IpcEvents;
